import { create } from 'zustand';
export type LocalModel = {role:string;endpoint:string;model:string|null;availableModels:string[];connected:boolean;error:string|null};
export type Runtime = {connected:boolean;vaultName:string;vaultPath:string;obsidianConfigured:boolean;noteCount:number;role:string;canWrite:boolean;writeFolder:string;retrieval:string;checkedAt:string;models:LocalModel[];network:{scope:string;externalInferenceAllowed:boolean;requests:{at:string;endpoint:string;model:string;jobId:string}[]}};
export type VaultNote = {id:string;name:string;folder:string;content?:string;metadata:Record<string,unknown>;links:string[];backlinks?:string[];sha256:string;obsidianUri:string;modified:string;evidenceId?:string};
export type VaultPage = {items:VaultNote[];total:number;page:number;pages:number};
export type VaultGraph = {nodes:{id:string;label:string;folder:string}[];edges:{source:string;target:string}[]};
export type LocalJob = {id:string;objective:string;kind:string;model:LocalModel;status:'running'|'review'|'failed'|'cancelled';events:{label:string;detail:string;at:string}[];output:string;sources:{id:string;evidenceId:string;sha256:string}[];createdAt:string;completedAt?:string;error?:string;verification?:string};
export type WritePreview = {id:string;title:string;path:string;content:string;finalContent:string;sha256:string;expectedSha256:string;expiresAt:number;role:string;status:string};
export type WriteReceipt = {path:string;sha256:string;at:string;role:string;obsidianUri:string;status:string};
export async function request<T>(path:string, body?:unknown, signal?:AbortSignal):Promise<T> {
 const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),12000);const abort=()=>controller.abort();signal?.addEventListener('abort',abort,{once:true});
 try {const response=await fetch(`/api${path}`,{method:body===undefined?'GET':'POST',headers:body===undefined?undefined:{'Content-Type':'application/json','X-Sentinel-Request':'workbench'},body:body===undefined?undefined:JSON.stringify(body),signal:controller.signal});const raw=await response.text();let data;try{data=JSON.parse(raw)}catch{throw new Error('The local API is not available. Start the Sentinel gateway and retry.')}if(!response.ok)throw new Error(data.error||`Local API returned ${response.status}`);return data as T;}catch(error){if(controller.signal.aborted)throw new Error('The local service did not respond in time. Retry when it is available.');throw error;}finally{clearTimeout(timeout);signal?.removeEventListener('abort',abort);}
}
export const localApi={status:()=>request<Runtime>('/health'),notes:(query='',page=1,signal?:AbortSignal)=>request<VaultPage>(`/vault/notes?q=${encodeURIComponent(query)}&page=${page}`,undefined,signal),note:(id:string,signal?:AbortSignal)=>request<VaultNote>(`/vault/note?id=${encodeURIComponent(id)}`,undefined,signal),graph:()=>request<VaultGraph>('/vault/graph'),jobs:()=>request<{items:LocalJob[]}>('/jobs'),job:(id:string)=>request<LocalJob>(`/jobs/${id}`),start:(objective:string,sourceIds:string[],kind:string)=>request<LocalJob>('/jobs',{objective,sourceIds,kind}),cancel:(id:string)=>request<LocalJob>(`/jobs/${id}/cancel`,{}),preview:(title:string,content:string,expectedSha256='')=>request<WritePreview>('/vault/preview',{title,content,expectedSha256}),commit:(id:string,sha256:string)=>request<WriteReceipt>('/vault/commit',{id,sha256})};
export const useLocal = create<{runtime:Runtime|null;error:string;loading:boolean;notes:VaultNote[];graph:VaultGraph|null;selectedSources:string[];objective:string;jobs:LocalJob[];refresh:()=>Promise<void>;selectSource:(id:string)=>void;setObjective:(objective:string)=>void;setJobs:(jobs:LocalJob[])=>void}>((set)=>({runtime:null,error:'',loading:false,notes:[],graph:null,selectedSources:[],objective:'',jobs:[],setJobs:jobs=>set({jobs}),setObjective:objective=>set({objective}),selectSource:id=>set(s=>({selectedSources:s.selectedSources.includes(id)?s.selectedSources.filter(x=>x!==id):s.selectedSources.length<8?[...s.selectedSources,id]:s.selectedSources})),refresh:async()=>{set({loading:true,error:''});try{const runtime=await localApi.status();const [notes,graph,jobs]=await Promise.all([localApi.notes(),localApi.graph().catch(()=>null),localApi.jobs()]);set({runtime,notes:notes.items,graph,jobs:jobs.items,loading:false});}catch(error){set({runtime:null,notes:[],graph:null,loading:false,error:error instanceof Error?error.message:'Could not connect to local services.'})}}}));
